main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<int:id>", views.index, name = "index"),  
    path("home", views.home, name = "home"),
    path("", views.home, name = "home"),
    path("create/", views.create, name = "create"),
    path("academicians/<str:name>", views.academician, name = "academician"),  
    path("academicians", views.academicians, name = "academicians"),
    path("my-comments", views.mycomments, name = "mycomments"),
    path("lectures", views.lectures, name = "lectures"),
    path("lectures/<str:name>", views.lecture, name = "lecture"),
    path("delete_comment/<comment_id>", views.delete_comment, name = "delete-comment"),
    path("profile", views.profile, name = "profile"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name = "register"),
    path('', include("main.urls")),
    path('', include("django.contrib.auth.urls")),
    path('activate<uidb64>/<token>/', v.activate, name='activate'),  
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete = models.CASCADE)
    text =  models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

class Department(models.Model):
    name = models.CharField(max_length=500)
    def __str__(self):
        return self.name

class Academician(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, on_delete = models.CASCADE)
    def __str__(self):
        return self.name

class Lecture(models.Model):
    name = models.CharField(max_length=400)
    academician = models.ManyToManyField(Academician)
    def __str__(self):
        return self.name

RATE_CHOICES = [
    (1, "1 - Very Bad"),
    (2, "2 - Bad"),
    (3, "3 - Neutral"),
    (4, "4 - Good"),
    (5, "5 - Very Good")
]

class Comment(models.Model):
    academician = models.ForeignKey(Academician, on_delete = models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete = models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name= "user", null=True)
    rating = models.PositiveSmallIntegerField(choices = RATE_CHOICES, null = True)
    text =  models.CharField(max_length=10000)
    live = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add= True)


    def __str__(self):
        return self.text

main/forms.py
from socket import fromshare
from django import forms
from .models import Academician, Comment

class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    check = forms.BooleanField(required=False)

class CommentAcademician(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ["academician", "user"]

class CommentLecture(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ["lecture", "user"]
    
        

main/views.py
from cgitb import text
from site import USER_BASE
from urllib import request
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ToDoList, Item, Academician, Comment, Lecture
from .forms import CommentAcademician, CreateNewList, CommentLecture
from django.contrib.auth.models import User
from django.db.models import Avg, Count



# Create your views here.

def index(response, id):
    ls = ToDoList.objects.get(id = id)
 
    if response.method == "POST":
        print(response.POST)
        if response.POST.get("save"):
            for item in ls.item_set.all():
                if response.POST.get("c" + str(item.id)) == "clicked":
                    item.complete = True
                else:
                    item.complete = False
                
                item.save()

        elif response.POST.get("newItem"):
            txt = response.POST.get("new")
            if len(txt) > 2:
                ls.item_set.create(text = txt, complete = False)
            else:
                print("invalid")


    return render(response, "main/list.html", {"ls": ls})

def home(response):
    return render(response, "main/home.html", {})

    
    
    

def create(response):
    if response.method == "POST":
        form = CreateNewList(response.POST)

        if form.is_valid():
            n = form.cleaned_data["name"]
            t = ToDoList(name = n)
            t.save()

    else:
        form = CreateNewList()

    return render(response, "main/create.html", {"form" : form})

def academician(response, name):
    user = response.user
    academician = Academician.objects.get(name = name)
    lectures = academician.lecture_set.all().order_by("name")
    form = CommentAcademician()
    form.fields["lecture"].queryset = Lecture.objects.filter(academician__name__startswith = academician.name)
    
    comment = Comment.objects.all()
    rating_avg = Comment.objects.filter(academician = academician.id).aggregate(rating_avg = Avg('rating'), comment_count = Count("text"))
    rating_avg["rating_avg"] = round(rating_avg["rating_avg"],2)
    if response.method == "POST":
        form = CommentAcademician(response.POST,  response.FILES)
        if form.is_valid():
            form.instance.academician = Academician.objects.get(name = name)
            form.instance.user = response.user
            form.save()

    return render(response, "main/academician.html", {"academician" : academician, "form" : form, "comment" : comment, "user" : user, "lectures" : lectures, "rating_avg" : rating_avg })

def lecture(response, name):
    user = response.user
    lecture = Lecture.objects.get(name = name)
    form = CommentLecture()
    form.fields["academician"].queryset = Academician.objects.filter(lecture__name__startswith = lecture.name)
    academicians = Academician.objects.all()
    comment = Comment.objects.all()

    if response.method == "POST":
        form = CommentLecture(response.POST,  response.FILES)
        if form.is_valid():
            form.instance.lecture = Lecture.objects.get(name = name)
            form.instance.user = response.user
            form.save()
    
    return render(response, "main/lecture.html", {"lecture" : lecture, "form" : form, "comment" : comment, "user" : user, "academicians" : academicians})

def academicians(response):
    academicians = Academician.objects.all().order_by("name")

    return render(response, "main/academicians.html", {"academicians" : academicians})

def mycomments(response):
    user = response.user
    comments = Comment.objects.all()
    return render(response, "main/my-comments.html",{"user" : user, "comments" : comments})

def delete_comment(response, comment_id):
    comment = Comment.objects.get(id = comment_id)
    comment.delete()

    return redirect("/my-comments")



def lectures(response):
    lectures = Lecture.objects.all().order_by("name")
    return render(response, "main/lectures.html", {"lectures" : lectures})

def profile(response):
    comments = Comment.objects.all().filter(user = response.user )
    return render(response, "main/profile.html", {"comments" : comments})

main/templates/main/academician.html
{% extends 'main/base.html' %}

{% block title %}{{academician.name}}{% endblock %}

{% block content %}

{% if user.is_authenticated %}

    <h3>{{academician.name}} <span class="badge bg-secondary">{{rating_avg.rating_avg}}/5</span> </h3>
   
    Lectures: &nbsp&nbsp
        {% for item in lectures %}
            <a style="color:blue; text-decoration: none " href="../lectures/{{item}}"  >
                {{item.name}} 
            </a> &nbsp&nbsp&nbsp
        {% endfor %}
        

    <hr>
     
    <h4>Comments</h4>

    {% for item in academician.comment_set.all %}

        <div class="card">
            <div class="card-header">
                {% for com in comment %}
                    {% if item.id == com.id %}
                        {{com.lecture}} [{{com.rating}}/5]<span style="float:right;">{{com.user.username}}</span>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-body">
                <p>{{item.text}}</p> 
            </div>
            <div class="card-footer">
                {{item.created_at}}
            </div>
        </div>
        <br>    
    {% endfor %}

    <hr>
    <br>
    
    <h4>Comment</h4>
    <form action="" method="post">
        {% csrf_token %}
        <select class="form-select" aria-label="Default select example" name="lecture" id="id_lecture">
            <option selected>Choose a lecture</option>
                {% for item in academician.lecture_set.all %}
                <option value="{{item.id}}">{{item.name}}</option>
                {% endfor %}
        </select>
        <br>
        <select class="form-select" aria-label="Default select example" name="rating" id="id_rating">
            <option selected>Rate your experience</option>
            {{form.rating.1}}
            {{form.rating.2}}
            {{form.rating.3}}
            {{form.rating.4}}
            {{form.rating.5}}
        </select>
        <br>
        <textarea type="text" class="form-control" name="text" maxlength="10000" required id="id_text" cols="70" rows="8" placeholder="Comment here..."></textarea>
        <br>
        <button type="submit" name="newComment" value="newComment" class="btn btn-success">Comment</button>
    </form>

{% else %}
<a href="/login">Login</a> to see the content
{% endif %}

{% endblock %}

main/templates/main/academicians.html
{% extends 'main/base.html' %}

{% block title %}
Academicians
{% endblock %}




{% block content %}
    {% if user.is_authenticated %}
    <h1>Academicians</h1>
    <hr>
    <div class="list-group">
        
        {% for item in academicians%}
            {% if item.name != "NOACA" %}
            <a href="academicians/{{item}}" class="list-group-item list-group-item-action" aria-current="true">
                {{item}} <span style="float:right;">({{item.comment_set.all.count}} comments)</span>
            </a>
            {% endif %}
        {% endfor %}

      </div>
    {% else %}

    <a href="/login">Login</a> to see the content

    {% endif %}
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <style type="text/css">
        .sidenav{
            height: 100%;
            width: 180x;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color:black;
            overflow-x: hidden;
            padding-top: 20px;
        }
        .sidenav a {
            padding: 20px 8px 6px 20px;
            text-decoration: none;
            color: #818181;
            font-size: 20px;
            display: block;
        }
        .sidenav a:hover{
            color:#f1f1f1;
        }
        .main{
            margin-left: 175px;
            padding: 0px 30px;
            margin-right: 0px;
        }
        /* The side navigation menu */
        .sidebar {
        margin: 0;
        padding: 0;
        width: 180px;
        background-color: #000000;
        position: fixed;
        height: 100%;
        overflow: auto;
        }

        /* Sidebar links */
        .sidebar a {
        display: block;
        color: white;
        padding: 16px;
        text-decoration: none;
        }

        /* Active/current link */
        .sidebar a.active {
        background-color: #04AA6D;
        color: white;
        }

        /* Links on mouse-over */
        .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
        }

        /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
        div.content {
        margin-left: 200px;
        padding: 1px 16px;
        }

        /* On screens that are less than 700px wide, make the sidebar into a topbar */
        @media screen and (max-width: 700px) {
        .sidebar {
            width: auto;
            height: auto;
            position: relative;
        }	
        .sidebar a {float: top;}
        div.content {margin-left: 0px;}
	
	.main{
            margin-left: 0px;
            padding: 0px 30px;
            margin-right: 0px;
        }
	}

        
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="sidebar">
        <a class="navbar-brand" href="/">
            <img src="https://dl.airtable.com/.attachments/5cce171110fa34da4c61caaad18c9b5d/8e0ee705/logo.png" alt="Logo" width=120  class="d-inline-block align-text-top">
          </a>
        <a href="/home">Home</a>
        <a href="/academicians">Academicians</a>
        <a href="/lectures">Lectures</a>
        <span style="align-items: bottom;">
            {% if user.is_authenticated %}
            <a href="/profile">Profile</a>
            <a href="/my-comments">My Comments</a>
            <a href="/logout">Log Out</a>
            {% else %}
            <a href="/login">Login</a>
            {% endif %}
        </span>
        

    </div>
    
    <div id="content" name="content" class="main">
        <div class="row justify-content-left">   
            <div class="col-11">
                <br>

                    {% block content %}
                    {% endblock %} 

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>


</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %}Create New List{% endblock %}

{% block content %}
<br>
<form action="/create/" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <button type="submit" name="save" class="btn btn-success">Create New</button>
        </div>  
        {{form.name}}
    </div>
</form>
{% endblock %}

main/templates/main/home.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <style type="text/css">
        .bg {
        position: fixed; 
        top: 0; 
        left: 180; 
            
        /* Preserve aspet ratio */
        min-width: 90%;
        min-height: 100%;
        }
        .main{
            margin-left: 180px;
            padding: 0px 0px;
            margin-right: 20px;

        }
        /* The side navigation menu */
        .sidebar {
        margin: 0;
        padding: 0;
        width: 180px;
        background-color: #000000;
        position: fixed;
        height: 100%;
        overflow: auto;
        }

        /* Sidebar links */
        .sidebar a {
        display: block;
        color: white;
        padding: 16px;
        text-decoration: none;
        }

        /* Active/current link */
        .sidebar a.active {
        background-color: #04AA6D;
        color: white;
        }

        /* Links on mouse-over */
        .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
        }

        /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
        div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
        }

        @media screen and (max-width: 700px) {
	.sidebar {padding-top: 10px;}
  	.sidebar a {font-size: 18px;}
        }   
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="sidebar">
        <a class="navbar-brand" href="/">
            <img src="https://dl.airtable.com/.attachments/5cce171110fa34da4c61caaad18c9b5d/8e0ee705/logo.png" alt="Logo" width=120  class="d-inline-block align-text-top">
          </a>
        <a href="/home">Home</a>
        <a href="/academicians">Academicians</a>
        <a href="/lectures">Lectures</a>
        <span style="align-items: bottom;">
            {% if user.is_authenticated %}
            <a href="/profile">Profile</a>
            <a href="/my-comments">My Comments</a>
            <a href="/logout">Log Out</a>
            {% else %}
            <a href="/login">Login</a>
            {% endif %}
        </span>
        

    </div>
   
    <div id="content" name="content" class="main">
        <div class="row justify-content-left">   
            <div class="col-8">
		<img src="https://dl.airtable.com/.attachments/7326a950a45e46e9da2ddb1dabba1670/7a3791ef/bilim_agaci.webp" alt="Banner" class="bg" >
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/lecture.html
{% extends 'main/base.html' %}

{% block title %}{{lecture.name}}{% endblock %}

{% block content %}

{% if user.is_authenticated %}

    <h3>{{lecture.name}}</h3>
    <hr>
    <h3>Comments</h3>
    {% for item in lecture.comment_set.all %}

        <div class="card">
            <div class="card-header">
                {{item.academician}}
                {% for com in comment %}
                    {% if item.id == com.id %}
                        [{{com.rating}}/5]<span style="float:right;">{{com.user.username}}</span>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-body">
                <p>{{item.text}}</p> 
            </div>
            <div class="card-footer">
                {{item.created_at}}
            </div>
        </div>
        <br>    
    {% endfor %}

    <hr>
    <br>

    <form action="" method="post">
        {% csrf_token %}
        <h4>Comment</h4><br>
        <select class="form-select" aria-label="Default select example" name="academician" id="id_academician">
            <option selected>Choose an academician</option>
            {% for acas in academicians %}                    
                {% for lec in acas.lecture_set.all %}                    
                    {% if lec.name == lecture.name %}
                    <option value="{{acas.id}}">{{acas.name}}</option>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </select>
        <br>

        

        <select class="form-select" aria-label="Default select example" name="rating" id="id_rating">
            <option selected>Rate your experience</option>
            {{form.rating.1}}
            {{form.rating.2}}
            {{form.rating.3}}
            {{form.rating.4}}
            {{form.rating.5}}
        </select>
          
        <br>
        <textarea type="text" class="form-control" name="text" maxlength="10000" required id="id_text" cols="70" rows="8" placeholder="Comment here..."></textarea>
        <br>
        <button type="submit" name="newComment" value="newComment" class="btn btn-success">Comment</button>
    </form>


{% else %}
<a href="/login">Login</a> to see the content
{% endif %}

{% endblock %}

main/templates/main/lectures.html
{% extends 'main/base.html' %}

{% block title %}
Lectures
{% endblock %}




{% block content %}
    {% if user.is_authenticated %}
    <h1>Lectures</h1>
    <hr>
    <div class="list-group">
        
        {% for item in lectures %}
          {% if item.name != "NOLEC" %}
            <a href="lectures/{{item}}" class="list-group-item list-group-item-action" aria-current="true">
                {{item}} <span style="float:right;">({{item.comment_set.all.count}} comments)</span>
          </a>
          {% endif %}
        {% endfor %}

      </div>
    {% else %}

    <a href="/login">Login</a> to see the content

    {% endif %}
{% endblock %}

main/templates/main/list.html
{% extends "main/base.html" %}

{% block title %}View List{% endblock %}

{% block content %}
    <h1>{{ls.name}}</h1>
    <form action="#" method="post">
        {% csrf_token %}
        {% for item in ls.item_set.all %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                {% if item.complete == True %}
                    <input type="checkbox" value="clicked" name="c{{item.id}}" checked>
                {% else %}
                    <input type="checkbox" value="clicked" name="c{{item.id}}">
                {% endif %}
                </div>
            </div>
            <input type="   " value="{{item.text}}" class="form-control">
        </div>
        
        {% endfor %}
        
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <button type="submit" name="newItem" value="newItem" class="btn btn-success">Add Item</button>
            </div>
            <input type="text" name="new"> 
        </div>
        <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
</form>
{% endblock %}

main/templates/main/my-comments.html
{% extends "main/base.html" %}

{% block title %}My Comments{% endblock %}

{% block content %}
<h1>My Comments</h1>
<hr>
    {% for each in comments%}
    {% if each.user.id == user.id %}
    <div class="card">
        <div class="card-header">
            {{each.lecture}} [{{each.academician.name}}]
        </div>
        <div class="card-body">
            <p>{{each.text}}</p> 
        </div>
        <div class="card-footer">
             
            <div align ="right">
                <span style="float:left;">{{each.created_at}}</span>
                <a href="{% url 'delete-comment' each.id %}" class="btn btn-danger" >Delete</a> 
            </div>
        </div>
    </div>
    <br>
    {% endif %}    
{% endfor %}

{% endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}    
    <h1>Profile</h2>
    <div class="card">
        <div class="card-body">
            Username = {{user}}
            <br>
            Email = {{user.email}}
            <br>
            Total Comments: {{comments.count}}
        </div>
      </div>
    
{% else %}
<a href="/login">Login</a> to see the content
{% endif %}

{% endblock %}